import argparse
import numpy as np

parser = argparse.ArgumentParser()
#parser.add_argument("sorting_algorithm", help = "Type of sorting algorithm to sort the 'random array'.", choices=["bubble","selection"])
parser.add_argument("--user_array", help = "Array of randomly ordered numbers input by the user.", nargs="*")
parser.add_argument("--random_array", help = "Array of randomly ordered numbers generated by the program. Only two arguments should be passed under --random_array. The first argument determines the maximum possible value of the elements in the random array and the second argument determines the size of the array.", nargs="*", type = int)

args = parser.parse_args()

values = args.user_array
randarr = args.random_array

print(values)
print(randarr)


if values:
    array = [values[num] for num in range(len(values))]
if randarr:
    random_array = np.random.randint(randarr[0], size = randarr[1])

print(array)
print(random_array)
